In [1]:
import pandas

In [2]:
df= pandas.read_csv('product_activity.csv')

1. ESTRUCTURA DEL DATAFRAME

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8782 entries, 0 to 8781
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            8782 non-null   str
 1   created_at         8782 non-null   str
 2   country            8782 non-null   str
 3   plan_type          8782 non-null   str
 4   user_age           8028 non-null   float64
 5   post_id            8782 non-null   str
 6   post_category      8782 non-null   str
 7   post_created_at    8782 non-null   str
 8   votes_received     8782 non-null   int64
 9   user_total_posts   8782 non-null   int64
 10  days_since_signup  8782 non-null   int64
 11  device_type        8782 non-null   str
dtypes: float64(1), int64(3), str(8)
memory usage: 823.4 KB

In [4]:
print('Dimensiones m x n')
df.shape

print('Nulos')
nulos_por_columna = df.isnull().sum()
print(nulos_por_columna)

Dimensiones m x n
Nulos
user_id                0
created_at             0
country                0
plan_type              0
user_age             754
post_id                0
post_category          0
post_created_at        0
votes_received         0
user_total_posts       0
days_since_signup      0
device_type            0
dtype: int64

In [5]:
total_duplicados = df.duplicated().sum()
print(total_duplicados)

172

In [6]:
df['country'].value_counts()

country
US    1928
BR    1656
AR    1199
PY     859
MX     835
CL     569
ES     568
CO     510
PE     403
UY     255
Name: count, dtype: int64

In [7]:
#elementos unicos
df['plan_type'].nunique()

19

In [8]:
df['plan_type'].value_counts()

plan_type
free            5978
pro             1460
enterprise       306
Free             208
 free            197
FREE             196
FreE             189
PRo               46
 pro              44
PRO               44
Pro               38
Pro               35
EnterPrise        13
ENTERPRISE        11
 enterprise        7
Enterprise         7
premium            1
vip                1
enterprise+        1
Name: count, dtype: int64

In [9]:
df['device_type'].nunique()

6

In [10]:
df['device_type'].value_counts()

device_type
web        4416
mobile     3761
desktop     602
tablet        1
console       1
phone         1
Name: count, dtype: int64

In [11]:
df['post_category'].value_counts()

post_category
tech           1187
life            913
sports          899
science         753
finance         739
gaming          727
music           614
health          601
education       592
travel          445
 tech            70
Tech             67
TECH             56
tehc             50
Life             46
Finance          44
 sport           42
sciense          42
gamming          40
 life            38
SPORTS           37
 finance         37
LIFE             36
Sports           36
 science         35
sporst           35
Gaming           35
Science          34
 gaming          33
SCIENCE          33
finanse          32
FINANCE          31
EDUCATION        31
educatoin        31
Music            28
healt            28
 health          26
Education        25
GAMING           22
 education       21
Health           21
MUSIC            21
lfe              21
 music           20
Travel           20
TRAVEL           19
HEALTH           18
 travel          16
trvael           16
musc             16
politics          1
mistery           1
sp0rts            1
Name: count, dtype: int64

In [12]:
df['post_category'].nunique()

53

Normalizando plan_type

In [13]:
df['plan_type_clean']=df['plan_type'].str.strip().str.lower()
df['plan_type_clean'].value_counts()

plan_type_clean
free           6768
pro            1667
enterprise      344
premium           1
vip               1
enterprise+       1
Name: count, dtype: int64

In [14]:
plan_type_map={
    'enterprise+':'enterprise'
}
df['plan_type_clean']=df['plan_type_clean'].replace(plan_type_map)

In [15]:
df['plan_type_clean'].value_counts()

plan_type_clean
free          6768
pro           1667
enterprise     345
premium          1
vip              1
Name: count, dtype: int64

In [16]:
plan_type_map={
    'pro':'pro',
    'free':'free',
    'enterprise':'enterprise'
}
df['plan_type_clean']=df['plan_type_clean'].map(plan_type_map)

In [17]:
df['plan_type_clean'].value_counts()

plan_type_clean
free          6768
pro           1667
enterprise     345
Name: count, dtype: int64

In [18]:
plan_type_fuera= df['plan_type_clean'].isnull()
plan_type_fuera

0       False
1       False
2       False
3       False
4       False
        ...
8777    False
8778    False
8779    False
8780    False
8781    False
Name: plan_type_clean, Length: 8782, dtype: bool

Normalizar device_type

In [19]:
device_type_map={
    'web':'web',
    'mobile':'mobile',
    'desktop': 'desktop'
}

df['device_type_clean']=df['device_type'].map(device_type_map)
df['device_type_clean'].value_counts()

device_type_clean
web        4416
mobile     3761
desktop     602
Name: count, dtype: int64

In [20]:
device_type_fuera=df['device_type_clean'].isnull()

In [21]:
df['post_category_clean']=df['post_category'].str.strip().str.lower()
df['post_category_clean'].value_counts()

post_category_clean
tech         1380
life         1033
sports        972
science       855
finance       851
gaming        817
music         683
education     669
health        666
travel        500
tehc           50
sport          42
sciense        42
gamming        40
sporst         35
finanse        32
educatoin      31
healt          28
lfe            21
trvael         16
musc           16
politics        1
mistery         1
sp0rts          1
Name: count, dtype: int64

In [22]:
post_category_map= {
    "tech":"tech", 
    "life": "life", 
    "sports": "sports", 
    "science": "science", 
    "finance": "finance", 
    "gaming": "gaming", 
    "music": "music", 
    "health": "health", 
    "education": "education", 
    "travel": "travel",
    "tehc":"tech", 
    "lfe": "life", 
    "sport": "sports", 
    "sp0rts": "sports", 
    "sporst": "sports", 
    "finanse": "finance", 
    "sciense": "science", 
    "musc": "music", 
    "healt": "health", 
    "educatoin": "education", 
    "trvael": "travel",
    "gamming": "gaming"
}
df['post_category_clean']=df['post_category_clean'].replace(post_category_map)
df['post_category_clean'].value_counts()

post_category_clean
tech         1430
life         1054
sports       1050
science       897
finance       883
gaming        857
education     700
music         699
health        694
travel        516
politics        1
mistery         1
Name: count, dtype: int64

In [23]:
post_category_map= {
    "tech":"tech", 
    "life": "life", 
    "sports": "sports", 
    "science": "science", 
    "finance": "finance", 
    "gaming": "gaming", 
    "music": "music", 
    "health": "health", 
    "education": "education", 
    "travel": "travel"
}

df['post_category_clean']=df['post_category_clean'].map(post_category_map)

df['post_category_clean'].value_counts()

post_category_clean
tech         1430
life         1054
sports       1050
science       897
finance       883
gaming        857
education     700
music         699
health        694
travel        516
Name: count, dtype: int64

In [24]:
post_category_fuera=df['post_category_clean'].isnull()
post_category_fuera

0       False
1       False
2       False
3       False
4       False
        ...
8777    False
8778    False
8779    False
8780    False
8781    False
Name: post_category_clean, Length: 8782, dtype: bool

In [25]:
print(plan_type_fuera.sum())     
print(device_type_fuera.sum())    
print(post_category_fuera.sum())

2
3
2

Quarantine

In [26]:
q_plan = df.loc[plan_type_fuera].copy()
q_plan['reason_code'] = 'plan_type_out_of_dictionary'

q_device = df.loc[device_type_fuera].copy()
q_device['reason_code'] = 'device_type_out_of_dictionary'

q_category = df.loc[post_category_fuera].copy()
q_category['reason_code'] = 'post_category_out_of_dictionary'

print(q_category)
print(q_device)
print(q_plan)

     user_id           created_at country plan_type  user_age   post_id  \
8775  U20004  2024-11-20T14:30:00      AR       pro      41.0  P0099004
8776  U20005  2025-06-01T00:00:00      CL       vip      27.0  P0099005

     post_category      post_created_at  votes_received  user_total_posts  \
8775      politics  2024-11-25T09:00:00               6                 7
8776       mistery  2025-06-02T00:00:00               3                 1

      days_since_signup device_type plan_type_clean device_type_clean  \
8775                  5     desktop             pro           desktop
8776                  1     console             NaN               NaN

     post_category_clean                      reason_code
8775                 NaN  post_category_out_of_dictionary
8776                 NaN  post_category_out_of_dictionary
     user_id           created_at country plan_type  user_age   post_id  \
8774  U20003  2025-01-05T08:00:00      US      free      22.0  P0099003
8776  U20005  2025-06-01T00:00:00      CL       vip      27.0  P0099005
8781  U20010  2025-09-01T05:05:05      ES      free       NaN  P0099010

     post_category      post_created_at  votes_received  user_total_posts  \
8774        health  2025-01-07T18:00:00               1                 2
8776       mistery  2025-06-02T00:00:00               3                 1
8781          tech  2025-09-02T05:05:05               9                 1

      days_since_signup device_type plan_type_clean device_type_clean  \
8774                  2      tablet            free               NaN
8776                  1     console             NaN               NaN
8781                  1       phone            free               NaN

     post_category_clean                    reason_code
8774              health  device_type_out_of_dictionary
8776                 NaN  device_type_out_of_dictionary
8781                tech  device_type_out_of_dictionary
     user_id           created_at country plan_type  user_age   post_id  \
8773  U20002  2025-04-10T09:15:00      BR   premium      34.0  P0099002
8776  U20005  2025-06-01T00:00:00      CL       vip      27.0  P0099005

     post_category      post_created_at  votes_received  user_total_posts  \
8773       finance  2025-04-12T12:00:00               8                 5
8776       mistery  2025-06-02T00:00:00               3                 1

      days_since_signup device_type plan_type_clean device_type_clean  \
8773                  2      mobile             NaN            mobile
8776                  1     console             NaN               NaN

     post_category_clean                  reason_code
8773             finance  plan_type_out_of_dictionary
8776                 NaN  plan_type_out_of_dictionary

In [30]:
q_device

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type,plan_type_clean,device_type_clean,post_category_clean,reason_code
8774,U20003,2025-01-05T08:00:00,US,free,22.0,P0099003,health,2025-01-07T18:00:00,1,2,2,tablet,free,NaN,health,device_type_out_of_dictionary
8776,U20005,2025-06-01T00:00:00,CL,vip,27.0,P0099005,mistery,2025-06-02T00:00:00,3,1,1,console,NaN,NaN,NaN,device_type_out_of_dictionary
8781,U20010,2025-09-01T05:05:05,ES,free,NaN,P0099010,tech,2025-09-02T05:05:05,9,1,1,phone,free,NaN,tech,device_type_out_of_dictionary

In [31]:
df[df['device_type_clean'].isnull()]

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type,plan_type_clean,device_type_clean,post_category_clean
8774,U20003,2025-01-05T08:00:00,US,free,22.0,P0099003,health,2025-01-07T18:00:00,1,2,2,tablet,free,NaN,health
8776,U20005,2025-06-01T00:00:00,CL,vip,27.0,P0099005,mistery,2025-06-02T00:00:00,3,1,1,console,NaN,NaN,NaN
8781,U20010,2025-09-01T05:05:05,ES,free,NaN,P0099010,tech,2025-09-02T05:05:05,9,1,1,phone,free,NaN,tech

In [ ]:
df['created_at_dt']=pandas.to_datetime(df['created_at'], errors='coerce')
df['post_created_at_dt']=pandas.to_datetime(df['post_created_at'], errors='coerce')

fechas_no_parseadas=  df['created_at_dt'].isnull() | df['post_created_at_dt'].isnull()

print(fechas_no_parseadas.sum())

2

In [35]:
fechas_no_parseadas

0       False
1       False
2       False
3       False
4       False
        ...
8777    False
8778     True
8779    False
8780    False
8781    False
Length: 8782, dtype: bool

In [36]:
df[df['created_at_dt'].isnull() | df['post_created_at_dt'].isnull()]

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type,plan_type_clean,device_type_clean,post_category_clean,created_at_dt,post_created_at_dt
8772,U20001,2025-02-30T10:00:00,PY,pro,29.0,P0099001,tech,2025-03-01T10:00:00,4,3,1,web,pro,web,tech,NaT,2025-03-01 10:00:00
8778,U20007,2025-03-15T12:00:00,MX,enterprise,38.0,P0099007,science,2025-99-99T00:00:00,5,10,10,web,enterprise,web,science,2025-03-15 12:00:00,NaT

In [39]:
post_antes_signup=df['post_created_at_dt']< df['created_at_dt']
post_antes_signup.sum()

np.int64(100)

In [42]:
q_fechas_ilogica=df[post_antes_signup].copy()
q_fechas_ilogica['reason_code'] = 'post_before_signup'

q_fechas_invalidas = df[fechas_no_parseadas].copy()
q_fechas_invalidas['reason_code'] = 'unparseable_date'

In [45]:
df['days_since_signup_calculo']=(df['post_created_at_dt']-df['created_at_dt']).dt.days
no_coincide=df['days_since_signup_calculo']!=df['days_since_signup']
print(no_coincide.sum(),no_coincide.sum()/len(df)*100, '%')

4479 51.002049647005244 %

In [47]:
fechas_invalidas=fechas_no_parseadas | post_antes_signup
q_fechas=df[fechas_invalidas].copy()
q_fechas['reason_code'] = q_fechas.apply(lambda r: 'unparseable_date' if pandas.isnull(r['created_at_dt']) or pandas.isnull(r['post_created_at_dt'])
    else 'post_before_signup',axis=1)
q_fechas

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type,plan_type_clean,device_type_clean,post_category_clean,created_at_dt,post_created_at_dt,days_since_signup_calculo,reason_code
22,U01754,2025-01-17T07:05:21,US,free,39.0,P0007502,sports,2024-12-18T16:05:21,3,6,0,web,free,web,sports,2025-01-17 07:05:21,2024-12-18 16:05:21,-30.0,post_before_signup
170,U00707,2024-10-07T17:32:12,MX,pro,27.0,P0003002,gaming,2024-09-27T12:32:12,13,11,0,mobile,pro,mobile,gaming,2024-10-07 17:32:12,2024-09-27 12:32:12,-11.0,post_before_signup
204,U00503,2025-01-13T13:27:33,US,FREE,16.0,P0002095,health,2024-12-14T01:27:33,7,9,0,web,free,web,health,2025-01-13 13:27:33,2024-12-14 01:27:33,-31.0,post_before_signup
208,U01763,2024-12-02T12:42:25,BR,free,39.0,P0007543,music,2024-11-08T11:42:25,5,13,0,web,free,web,music,2024-12-02 12:42:25,2024-11-08 11:42:25,-25.0,post_before_signup
288,U01122,2024-04-28T09:03:25,US,pro,22.0,P0004783,education,2024-03-29T16:03:25,11,6,0,mobile,pro,mobile,education,2024-04-28 09:03:25,2024-03-29 16:03:25,-30.0,post_before_signup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8608,U01378,2025-06-19T18:02:45,US,pro,26.0,P0005902,travel,2025-05-20T09:02:45,8,22,0,mobile,pro,mobile,travel,2025-06-19 18:02:45,2025-05-20 09:02:45,-31.0,post_before_signup
8646,U00243,2025-02-03T13:41:27,PY,free,35.0,P0001060,finance,2025-01-31T12:41:27,2,15,0,mobile,free,mobile,finance,2025-02-03 13:41:27,2025-01-31 12:41:27,-4.0,post_before_signup
8772,U20001,2025-02-30T10:00:00,PY,pro,29.0,P0099001,tech,2025-03-01T10:00:00,4,3,1,web,pro,web,tech,NaT,2025-03-01 10:00:00,NaN,unparseable_date
8777,U20006,2025-05-10T00:00:00,PY,free,30.0,P0099006,travel,2025-05-09T23:00:00,2,4,0,web,free,web,travel,2025-05-10 00:00:00,2025-05-09 23:00:00,-1.0,post_before_signup
8778,U20007,2025-03-15T12:00:00,MX,enterprise,38.0,P0099007,science,2025-99-99T00:00:00,5,10,10,web,enterprise,web,science,2025-03-15 12:00:00,NaT,NaN,unparseable_date